FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root

COPY dashboard/backend ./dashboard/backend

WORKDIR /app/dashboard/backend

EXPOSE 8050

CMD ["python", "main.py"]
